### ISSUE TITLE
Description saved using CKEditor is not getting populated from database

### ISSUE THREAD

**Issue by nalumachurakesh** [idea2app/strapi-plugin-ckeditor#1]
Hi,

I upgraded default rich text editor of strapi to CKEditor in version 3.3 by referring to the steps in the link and it is working fine. I migrated strapi from 3.3 to 3.4, then the description is not getting populated in the UI from the database but it is getting from db in the api response.

### Steps to reproduce the behavior

1. Please follow this link to setup CKEditor
2. Save content using CKEditor
3. Reload the application and to pull the saved content in the CKEditor

### System

-Node.js version: v12.13.0
-NPM version: v6.12.0
-Strapi version: v3.4.1
-Database: sqlite
-Operating system: Windows 10

Please help me to resolve this. Thanks in advance.

**Comment by promentus** [comment]
Did you find a solution? I have the same problem..

**Comment by nalumachurakesh** [comment]
@promentus I followed the solution [here](https://github.com/strapi/strapi/issues/8984) provided
